version: '3.9'

volumes:
  guest_django_media: {}
  guest_django_static: {}
  partner_django_media: {}
  partner_django_static: {}
  admin_django_media: {}
  admin_django_static: {}
  nginx_log: {}

services:
  guest_service:
    container_name : guest_service
    image: <GUEST_IMAGE> #shell script will replace this
    entrypoint: sh -c "poetry run python manage.py collectstatic --no-input && poetry run python manage.py migrate && poetry run gunicorn config.wsgi --workers=5 -b 0.0.0.0:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - guest_django_media:/guest/media/
      - guest_django_static:/guest/static/
    environment:
      - DJANGO_SETTINGS_MODULE=<DJANGO_SETTINGS_MODULE> #shell script will replace this
    expose:
      - "8000"
    restart: always
    networks:
      - app_net

  partner_service:
    container_name : partner_service
    image: <PARTNER_IMAGE> #shell script will replace this
    entrypoint: sh -c "poetry run python manage.py collectstatic --no-input && poetry run python manage.py migrate && poetry run gunicorn config.wsgi --workers=5 -b 0.0.0.0:8001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - partner_django_media:/partner/media/
      - partner_django_static:/partner/static/
    environment:
      - DJANGO_SETTINGS_MODULE=<DJANGO_SETTINGS_MODULE> #shell script will replace this
    expose:
      - "8001"
    restart: always
    networks:
      - app_net

  admin_service:
    container_name : admin_service
    image: <ADMIN_IMAGE> # shell script will replace this
    entrypoint: sh -c "poetry run python manage.py collectstatic --no-input && poetry run python manage.py migrate && poetry run gunicorn config.wsgi --workers=5 -b 0.0.0.0:8002"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - admin_django_media:/admin/media/
      - admin_django_static:/admin/static/
    environment:
      - DJANGO_SETTINGS_MODULE=<DJANGO_SETTINGS_MODULE> # shell script will replace this
    expose:
      - "8002"
    restart: always
    networks:
      - app_net

  nginx:
    container_name : nginx
    image: nginx:1.25.3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nginx_log:/var/log/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - admin_django_media:/admin/media/
      - admin_django_static:/admin/static/
      - guest_django_media:/guest/media/
      - guest_django_static:/guest/static/
      - partner_django_media:/partner/media/
      - partner_django_static:/partner/static/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    networks:
      - app_net

  certbot:
    container_name: certbot
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
