version: '3.9'

volumes:
  web_app_django_media: {}
  web_app_django_static: {}
  # admin_django_media: {}
  # admin_django_static: {}
  nginx_log: {}

services:
  web_app:
    container_name: web_app
    build: ./web_app/
    entrypoint: sh -c "poetry run python manage.py collectstatic --no-input && poetry run python manage.py migrate && poetry run gunicorn config.wsgi --workers=5 -b 0.0.0.0:8000"
    volumes:
      - ./web_app/django/:/web_app/
      - /etc/localtime:/etc/localtime:ro
      - web_app_django_media:/web_app/media/
      - web_app_django_static:/web_app/static/
    environment:
      - DJANGO_SETTINGS_MODULE=config.django.dev
    expose:
      - "8000"
    restart: always

  # admin:
  #   container_name: admin
  #   build: ./admin/
  #   entrypoint: sh -c "poetry run python manage.py collectstatic --no-input && poetry run python manage.py migrate && poetry run gunicorn config.wsgi --workers=5 -b 0.0.0.0:8000"
  #   volumes:
  #     - ./admin/django/:/admin/
  #     - /etc/localtime:/etc/localtime:ro
  #     - admin_django_media:/admin/media/
  #     - admin_django_static:/admin/static/
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=config.django.dev
  #   expose:
  #     - "8001"
  #   restart: always

  nginx:
    container_name : nginx
    image: nginx:1.25.3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nginx_log:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - web_app_django_media:/web_app/media/
      - web_app_django_static:/web_app/static/
      # - admin_django_media:/admin/media/
      # - admin_django_static:/admin/static/
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
