version: "3.9"

volumes:
  postgres: {}

services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=github_actions
    restart: on-failure

  web_app:
    container_name: web_app
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    environment:
      - GITHUB_WORKFLOW=True
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure
