version: "3.9"

volumes:
  postgres: {}

services:
  postgres-db:
    image: postgres:16.2
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=github_actions
    restart: on-failure

  guest_service:
    build:
      context: .
      dockerfile: guest_service/docker/local.Dockerfile
    environment:
      - GITHUB_WORKFLOW=True
    command: poetry run python manage.py runserver
    volumes:
      - ./guest/:/guest_service/
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    restart: on-failure

  manager_service:
    build:
      context: .
      dockerfile: manager_service/docker/local.Dockerfile
    environment:
      - GITHUB_WORKFLOW=True
    command: poetry run python manage.py runserver
    volumes:
      - ./manager/:/manager_service/
    ports:
      - "8001:8001"
    depends_on:
      - postgres-db
    restart: on-failure

  admin_service:
    build:
      context: .
      dockerfile: admin_service/docker/local.Dockerfile
    environment:
      - GITHUB_WORKFLOW=True
    command: poetry run python manage.py runserver
    volumes:
      - ./admin/:/admin_service/
    ports:
      - "8002:8002"
    depends_on:
      - postgres-db
    restart: on-failure
