version: "3.9"

volumes:
  postgres: {}

services:
  postgres-db:
    image: postgres:16.2
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=github_actions
    restart: on-failure

  guest-service:
    build:
      context: .
      dockerfile: guest-service/docker/local.Dockerfile
    environment:
      - GITHUB_WORKFLOW=True
    command: poetry run python manage.py runserver
    volumes:
      - ./guest/:/guest-service/
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    restart: on-failure

  manager-service:
    build:
      context: .
      dockerfile: manager-service/docker/local.Dockerfile
    environment:
      - GITHUB_WORKFLOW=True
    command: poetry run python manage.py runserver
    volumes:
      - ./manager/:/manager-service/
    ports:
      - "8001:8001"
    depends_on:
      - postgres-db
    restart: on-failure

  admin-service:
    build:
      context: .
      dockerfile: admin-service/docker/local.Dockerfile
    environment:
      - GITHUB_WORKFLOW=True
    command: poetry run python manage.py runserver
    volumes:
      - ./admin/:/admin-service/
    ports:
      - "8002:8002"
    depends_on:
      - postgres-db
    restart: on-failure
