version: "3.9"

volumes:
  postgres: {}

services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=github_actions
    restart: on-failure

  guest:
    build:
      context: .
      dockerfile: guest/docker/local.Dockerfile
    environment:
      - GITHUB_WORKFLOW=True
    command: poetry run python manage.py runserver
    volumes:
      - ./guest/:/guest/
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure

  manager:
    build:
      context: .
      dockerfile: manager/docker/local.Dockerfile
    environment:
      - GITHUB_WORKFLOW=True
    command: poetry run python manage.py runserver
    volumes:
      - ./manager/:/manager/
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    restart: on-failure

  admin:
    build:
      context: .
      dockerfile: admin/docker/local.Dockerfile
    environment:
      - GITHUB_WORKFLOW=True
    command: poetry run python manage.py runserver
    volumes:
      - ./admin/:/admin/
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    restart: on-failure
