# Generated by Django 4.2.11 on 2024-03-15 21:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_kindergardens', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPetKindergarden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('thum_url', models.URLField(db_column='thumUrl')),
                ('tel', models.CharField(db_column='tel', max_length=16)),
                ('virtual_tel', models.CharField(blank=True, db_column='virtualTel', max_length=16)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('x', models.DecimalField(db_column='x', decimal_places=10, max_digits=13)),
                ('y', models.DecimalField(db_column='y', decimal_places=10, max_digits=13)),
                ('business_hours', models.CharField(db_column='businessHours', max_length=64)),
                ('address', models.CharField(db_column='address', max_length=128)),
                ('road_address', models.CharField(db_column='roadAddress', max_length=128)),
                ('abbr_address', models.CharField(db_column='abbrAddress', max_length=128)),
                ('short_address', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), db_column='shortAddress', size=10)),
            ],
            options={
                'verbose_name': 'raw pet kindergarden',
                'verbose_name_plural': 'raw pet kindergarden',
                'db_table': 'raw_pet_kindergarden',
            },
        ),
        migrations.AlterField(
            model_name='petkindergarden',
            name='guide_message',
            field=models.TextField(blank=True, verbose_name='안내 메시지'),
        ),
        migrations.AlterField(
            model_name='petkindergarden',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='전화번호'),
        ),
    ]
