# Generated by Django 4.2.11 on 2024-03-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_kindergardens', '0003_rawpetkindergarden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petkindergarden',
            name='profile_thumbnail_url',
            field=models.URLField(verbose_name='프로필 썸네일 이미지'),
        ),
    ]
