# Generated by Django 4.2.11 on 2024-03-14 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialProvider',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, db_column='user_social_provider_id', primary_key=True, serialize=False, verbose_name='유저 소셜 제공자 아이디')),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='설명')),
            ],
            options={
                'verbose_name': 'user social provider',
                'verbose_name_plural': 'user social providers',
                'db_table': 'T_user_social_provider',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='user_id', primary_key=True, serialize=False, verbose_name='유저 아이디')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('social_id', models.CharField(blank=True, unique=True, max_length=64, verbose_name='소셜 아이디')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
                ('gender', models.CharField(blank=True, max_length=1, verbose_name='성별')),
                ('birth', models.DateField(blank=True, verbose_name='생년월일')),
                ('phone_number', models.CharField(blank=True, max_length=16, verbose_name='전화번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='슈퍼유저 여부')),
                ('is_agree_privacy', models.BooleanField(default=True, verbose_name='개인정보 동의 여부')),
                ('is_agree_marketing', models.BooleanField(default=False, verbose_name='마케팅 정보 수신 동의 여부')),
                ('last_login', models.DateTimeField(blank=True, verbose_name='마지막 로그인 일시')),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.group', verbose_name='그룹')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='유저 권한')),
                ('user_social_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.usersocialprovider')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
